#ifndef HARDWARE_CONFIG_H
#define HARDWARE_CONFIG_H

#define PTT_INDICATOR_PIN 21
#define PTT_PIN 20
#define PTT_ON 1
#define PTT_OFF 0

#define SWITCH_INDICATOR_PIN 1
#define SWITCH_PIN 0
#define SWITCH_ON 0
#define SWITCH_OFF 1

#define RADIO_RFM_CS_PIN 13
#define RADIO_SX_CS_PIN 17

#define SPI1_MOSI_PIN 15
#define SPI1_MISO_PIN 12
#define SPI1_SCK_PIN 14

#define RADIO_RFM_RESET_PIN 9
#define RADIO_RFM_DIO1_PIN 10
#define RADIO_RFM_DIO0_PIN 11

#define RADIO_SX_NRESET_PIN 26
#define RADIO_SX_BUSY_PIN 22
#define RADIO_SX_DIO1_PIN 27

#define SPI_BUS_TX spi0
#define SPI_BUS_RX spi1

#define ERROR_LED_PIN 2

#endif