services:

  rigctld:
    image: 'librespace/hamlib:4.5.4'
    user: '999'
    read_only: true
    environment:
      MODEL: '1'
    restart: 'unless-stopped'
    command: 'rigctld'

  rotctld:
    image: 'librespace/hamlib:4.5.4'
    user: '999'
    group_add:
      - dialout
    read_only: true
    environment:
      MODEL: '603'
      SERIAL_SPEED: "9600"
      SET_CONF: 'min_az=0,max_az=430,min_el=5,max_el=180'
    device_cgroup_rules:
      - 'c 188:* rwm'
    devices:
      - '/dev/serial/by-id/usb-Prolific_Technology_Inc._USB-Serial_Controller_D-if00-port0:/dev/rot0'
    restart: 'unless-stopped'
    command: 'rotctld -r /dev/rot0 -m 603 -s 9600'
    stop_grace_period: 1s

  satnogs_client:
    build:
      context: .
      args:
        GNURADIO_IMAGE_TAG: '${GNURADIO_IMAGE_TAG:-3.10.5.1-satnogs}'
    image: 'satnogs-client'
    group_add:
      - plugdev
    user: '500:500'
    read_only: true
    device_cgroup_rules:
      - 'c 189:* rwm'
    environment:
      SATNOGS_API_TOKEN: 'SOME_API_TOKEN'
      SATNOGS_SOAPY_RX_DEVICE: 'driver=rtlsdr'
      SATNOGS_ANTENNA: 'RX'
      SATNOGS_RX_SAMP_RATE: '2.048e6'
      SATNOGS_RF_GAIN: "3.7"
      SATNOGS_STATION_ELEV: '390'
      SATNOGS_STATION_ID: '4682'
      SATNOGS_STATION_LAT: '33.42165'
      SATNOGS_STATION_LON: '-111.93167'
      SATNOGS_RIG_IP: 'rigctld'
      SATNOGS_ROT_MODEL: 'ROT_MODEL_NETROTCTL'
      SATNOGS_ROT_PORT: 'rotctld:4533'
      SATNOGS_LOG_LEVEL: "INFO"
    command: 'satnogs-client'
    volumes:
      - type: 'tmpfs'
        target: '/tmp'
      - type: 'volume'
        target: '/var/lib/satnogs-client'
      - '/dev/bus/usb:/dev/bus/usb'
      - '/dev/serial/by-id:/dev/serial/by-id'
    restart: 'unless-stopped'
